- hosts: kube_masters,kube_worknodes
  remote_user: admin1
  become: yes
  become_user: root
  tasks:

   - name: Wait 60 seconds before start VMs, but only start checking after 60 seconds
     wait_for_connection:
       delay: 1
       timeout: 60

   - name: add to hosts
     ansible.builtin.lineinfile:
       dest: /etc/hosts
       line: "{{ item }}"
     with_items:
       - 192.168.5.100 kube-m01
       - 192.168.5.101 kube-w01
       - 192.168.5.102 kube-w02

   - name: kuber prepare 1
     shell: 'curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg |  apt-key add -'

   - name: kuber prepare 2
     ansible.builtin.lineinfile:
       dest: /etc/apt/sources.list.d/kubernetes.list
       line: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
       create: yes

   - name: docker prepare 1
     ansible.builtin.file:
       path: /etc/docker
       state: directory

   - name: docker prepare 2
     ansible.builtin.copy:
       src: ./daemon.json
       dest: /etc/docker/daemon.json
       owner: root
       group: root
       mode: '0644'

   - name: update cache
     apt:
       update_cache: yes

   - name: install packages
     apt:
       state: latest
       install_recommends: yes 
       update_cache: yes
       pkg:
         - curl
         - wget
         - apt-transport-https
         - git
         - iptables-persistent
         - mc
         - htop
         - iotop
         - locate
         - mc
         - docker.io
         - kubelet
         - kubeadm
         - kubectl


   - name: load modules (add to autoplay)
     ansible.builtin.lineinfile:
       dest: /etc/modules-load.d/k8s.conf
       line: "{{ item }}"
       create: yes
     with_items:
       - br_netfilter
       - overlay

   - name: enable modules (add to autoplay)
     ansible.builtin.lineinfile:
       dest: /etc/sysctl.d/k8s.conf
       line: "{{ item }}"
       create: yes
     with_items:
       - "net.bridge.bridge-nf-call-ip6tables = 1"
       - "net.bridge.bridge-nf-call-iptables = 1"

   - name: add to enviroment kube config
     ansible.builtin.lineinfile:
       dest: /etc/environment
       line: "export KUBECONFIG=/etc/kubernetes/admin.conf"

   - name: start net modules
     shell: "modprobe br_netfilter && modprobe overlay && sysctl --system "

   - name: swapoff
     shell: "swapoff -a" 

   - name:  remove swap
     ansible.builtin.file:
       path: /swap.img
       state: absent

   - name: delete swap from fstab
     ansible.builtin.lineinfile:
      path: /etc/fstab
      regexp: 'swap.img'
      line: ''

   - name: dist upgrade
     apt:
       update_cache: yes
       autoclean: yes
       autoremove: yes
       upgrade: full
     register: task_result

   - name: Reboot immediately if there was a change.
     reboot:
       reboot_timeout: 36000

